### ISSUE TITLE
RebindingBC Bug

### ISSUE THREAD

**Issue by dixonth1silicon** [ADicksonLab/wepy#25]
Line 480 in receptor.py needs to be changed from:

```
        super().__init__(initial_states=initial_states,
                                 initial_weights=initial_weights,
                                 ligand_idxs=ligand_idxs,
                                 receptor_idxs=binding_site_idx
                                 **kwargs)

```

to 

        super().__init__(initial_states=initial_states,
                                 initial_weights=initial_weights
                                 ligand_idxs=ligand_idxs,
                                 receptor_idxs=binding_site_idxs,
                                 **kwargs)

**Comment by salotz-sitx** [comment]
Duplicate of #17
