### ISSUE TITLE
BC and REVO Resampler dashboard section not reporting correct information.

### ISSUE THREAD

**Issue by dixonth1silicon** [ADicksonLab/wepy#27]
The Resampling boundary condition dashboard section is not reporting cutoff RMSD to the dashboard. The REVO dashboard section is not reporting REVO parameters to the dashboard. 

Urgency: Low. 
While not ideal, this does not interfere with running simulations.

**Comment by austinjpaul** [comment]
This looks like it has a fix pending in #41. Any update as to its progress? @salotz-sitx

**Comment by salotz-sitx** [comment]
I was going to try and merge a bunch of other stuff I had ready in a private branch, but priorities shifted.

@austinjpaul If you can do a sanity test on that branch I could merge since its low impact.

**Comment by salotz** [comment]
Fixed by #41
