### ISSUE TITLE
multiple GPU

### ISSUE THREAD

**Issue by BK33333** [ADicksonLab/wepy#73]
Hi,
Could someone please help with setting up multiple gpu in WEPY?

in openmm i use the following

platform = Platform.getPlatformByName('CUDA')
platformProperties = {'CudaPrecision': 'mixed'}
platformProperties["CudaDeviceIndex"]= "0,1"

simulation = Simulation(topology, system, integrator, platform, platformProperties)

thanks,

**Comment by salotz** [comment]
The `TaskMapper` and `WorkerMapper` parallel work mappers both support multiple GPUs.

**Comment by salotz** [comment]
This is an issue more suited to discussions. I've just enabled the Github Discussions feature and if needed can be discussed mroe there.
